## Импорт библиотек и загрузка данных

In [1]:
import os
print(os.getcwd())
print(os.listdir())

d:\Programs\analysis.ipynb
['.git', 'ad_spend.csv', 'edtech_data.db', 'final_work_database.db', 'funnel_events.csv', 'main.ipynb', 'payments.csv', 'README.md', 'test_results.csv', 'trial_lessons.csv', 'users.csv']

In [2]:
import pandas as pd
import sqlite3
import os



# Создаем подключение к базе
conn = sqlite3.connect('edtech_data.db')

# Загружаем файлы напрямую (так как названия теперь нормальные)
# Заменяем read_sql на read_csv во второй строке загрузки
pd.read_csv('users.csv').to_sql('users', conn, if_exists='replace', index=False)
pd.read_csv('payments.csv').to_sql('payments', conn, if_exists='replace', index=False)
pd.read_csv('trial_lessons.csv').to_sql('trial_lessons', conn, if_exists='replace', index=False)
pd.read_csv('ad_spend.csv').to_sql('ad_spend', conn, if_exists='replace', index=False)
pd.read_csv('funnel_events.csv').to_sql('funnel_events', conn, if_exists='replace', index=False)
pd.read_csv('test_results.csv').to_sql('test_results', conn, if_exists='replace', index=False)

print("Все таблицы загружены!")

Все таблицы загружены!

# Все таблицы

In [3]:
query = "SELECT * FROM users LIMIT 1"
pd.read_sql(query, conn)

,user_id,first_visit_at,acquisition_channel,campaign,device,age_group,country,landing_page,user_goal
0,U00001,2026-02-05 14:14:00,YouTube,yt_pre_roll,mobile,18-24,Austria,trial_lesson,exam

In [4]:
query = "SELECT * FROM funnel_events LIMIT 1"
pd.read_sql(query, conn)

,event_id,user_id,event_time,event_name,step_order,acquisition_channel,campaign
0,E000001,U00001,2026-02-05 14:14:00,site_visit,1,YouTube,yt_pre_roll

In [5]:
query = "SELECT * FROM ad_spend LIMIT 1"
pd.read_sql(query, conn)

,date,acquisition_channel,campaign,spend_eur,impressions,clicks
0,2026-01-01,Instagram,ig_reels_beginner,31.45,5425,43

In [6]:
query = "SELECT * FROM trial_lessons LIMIT 1"
pd.read_sql(query, conn)

,user_id,trial_booked_at,trial_attended_at,trial_attended,teacher_rating
0,U00001,2026-02-06 04:48:00,2026-02-09 16:48:00,1,3.6

In [7]:
query = "SELECT * FROM payments LIMIT 50"
pd.read_sql(query, conn)

,payment_id,user_id,payment_date,plan_name,subscription_type,amount_eur,payment_status,refund_flag,acquisition_channel,campaign
0,P00001,U00010,2026-04-02,Basic Materials,monthly,29.0,success,0,YouTube,yt_long_form
1,P00002,U00028,2026-02-13,Basic Materials,monthly,29.0,success,0,Partner Referral,partner_creator
2,P00003,U00047,2026-03-27,Basic Materials,monthly,29.0,success,0,YouTube,yt_pre_roll
3,P00004,U00054,2026-02-02,Basic Materials,monthly,29.0,success,0,Telegram,tg_channel_post
4,P00005,U00058,2026-03-02,Basic Materials,monthly,29.0,success,0,YouTube,yt_teacher_expert
5,P00006,U00067,2026-03-20,Basic Materials,monthly,29.0,success,0,Google Ads,ga_competitor
6,P00007,U00074,2026-03-07,Intensive Plan,monthly,149.0,success,0,Partner Referral,partner_blog
7,P00008,U00075,2026-02-12,Basic Materials,monthly,29.0,failed,0,YouTube,yt_pre_roll
8,P00009,U00081,2026-01-02,Basic Materials,monthly,29.0,success,0,Instagram,ig_story_discount
9,P00010,U00082,2026-02-15,Speaking Club,monthly,49.0,success,0,YouTube,yt_long_form
10,P00011,U00093,2026-02-13,Basic Materials,monthly,29.0,success,0,Partner Referral,partner_blog
11,P00012,U00119,2026-02-15,Basic Materials,monthly,29.0,failed,0,YouTube,yt_pre_roll
12,P00013,U00130,2026-01-12,Speaking Club,monthly,49.0,failed,0,Google Ads,ga_competitor
13,P00014,U00131,2026-01-22,Speaking Club,monthly,49.0,success,0,Google Ads,ga_search_english_course
14,P00015,U00142,2026-03-18,Basic Materials,monthly,29.0,failed,0,Partner Referral,partner_hr_benefit
15,P00016,U00203,2026-03-15,Personal Tutor,monthly,99.0,failed,0,YouTube,yt_long_form
16,P00017,U00209,2026-01-05,Speaking Club,monthly,49.0,success,0,YouTube,yt_long_form
17,P00018,U00224,2026-02-28,Speaking Club,monthly,49.0,success,0,Partner Referral,partner_blog
18,P00019,U00231,2026-01-29,Intensive Plan,quarterly,149.0,success,0,YouTube,yt_pre_roll
19,P00020,U00233,2026-02-04,Speaking Club,monthly,49.0,success,0,Telegram,tg_webinar_invite
20,P00021,U00238,2026-02-19,Basic Materials,monthly,29.0,success,0,Google Ads,ga_search_english_course
21,P00022,U00251,2026-02-27,Intensive Plan,monthly,149.0,success,0,Google Ads,ga_search_english_course
22,P00023,U00254,2026-02-16,Basic Materials,monthly,29.0,success,0,YouTube,yt_long_form
23,P00024,U00263,2026-02-01,Basic Materials,monthly,29.0,success,0,YouTube,yt_pre_roll
24,P00025,U00264,2026-01-16,Personal Tutor,monthly,99.0,failed,0,Partner Referral,partner_blog
25,P00026,U00277,2026-01-16,Speaking Club,monthly,49.0,success,0,Google Ads,ga_competitor
26,P00027,U00279,2026-01-21,Speaking Club,monthly,49.0,success,0,Google Ads,ga_brand
27,P00028,U00289,2026-03-11,Basic Materials,monthly,29.0,success,0,Instagram,ig_story_discount
28,P00029,U00295,2026-02-22,Basic Materials,monthly,29.0,success,0,YouTube,yt_long_form
29,P00030,U00300,2026-02-09,Basic Materials,monthly,29.0,success,0,Partner Referral,partner_hr_benefit
30,P00031,U00312,2026-01-04,Personal Tutor,quarterly,99.0,success,0,Partner Referral,partner_hr_benefit
31,P00032,U00324,2026-03-03,Personal Tutor,monthly,99.0,success,0,Instagram,ig_story_discount
32,P00033,U00327,2026-03-24,Intensive Plan,monthly,149.0,success,0,Telegram,tg_community_native
33,P00034,U00333,2026-01-28,Personal Tutor,quarterly,99.0,success,0,Partner Referral,partner_hr_benefit
34,P00035,U00341,2026-01-25,Basic Materials,monthly,29.0,success,0,Google Ads,ga_search_english_course
35,P00036,U00354,2026-02-20,Basic Materials,monthly,29.0,success,0,YouTube,yt_teacher_expert
36,P00037,U00356,2026-03-27,Speaking Club,monthly,49.0,success,0,Telegram,tg_community_native
37,P00038,U00362,2026-02-19,Basic Materials,monthly,29.0,failed,0,Instagram,ig_story_discount
38,P00039,U00385,2026-02-19,Basic Materials,monthly,29.0,success,0,Google Ads,ga_competitor
39,P00040,U00388,2026-01-25,Basic Materials,monthly,29.0,failed,0,Instagram,ig_reels_beginner
40,P00041,U00390,2026-02-17,Intensive Plan,quarterly,149.0,success,0,YouTube,yt_long_form
41,P00042,U00391,2026-02-24,Basic Materials,monthly,29.0,success,0,Telegram,tg_community_native
42,P00043,U00394,2026-03-23,Speaking Club,monthly,49.0,success,0,Partner Referral,partner_creator
43,P00044,U00406,2026-03-21,Speaking Club,monthly,49.0,success,1,Telegram,tg_channel_post
44,P00045,U00425,2026-01-08,Basic Materials,monthly,29.0,success,0,Google Ads,ga_competitor
45,P00046,U00430,2026-01-10,Speaking Club,monthly,49.0,success,0,Instagram,ig_story_discount
46,P00047,U00443,2026-02-13,Speaking Club,monthly,49.0,success,0,Partner Referral,partner_creator
47,P00048,U00445,2026-02-08,Speaking Club,monthly,49.0,success,0,YouTube,yt_teacher_expert
48,P00049,U00457,2026-01-20,Personal Tutor,monthly,99.0,success,0,Google Ads,ga_competitor
49,P00050,U00477,2026-03-06,Personal Tutor,monthly,99.0,success,0,Partner Referral,partner_blog

In [8]:
query = "SELECT * FROM test_results LIMIT 1"
pd.read_sql(query, conn)

,user_id,test_started_at,test_completed_at,test_score,recommended_level,recommended_plan
0,U00001,2026-02-05 14:48:00,2026-02-05 15:13:00,66.0,B1,Speaking Club

# Подготовка данных

## Проверка количества строк в каждой таблице

Вывод: Объем выборки статистически значим; исключен риск анализа по единичным случаям

In [9]:
query = """SELECT COUNT(*) AS strings_users
,(SELECT COUNT(*) FROM funnel_events ) AS strings_funnel_events
,(SELECT COUNT(*) FROM test_results) AS strings_test_results
,(SELECT COUNT(*) FROM trial_lessons) AS strings_trial_lessons
,(SELECT COUNT(*) FROM payments) AS strings_payments
,(SELECT COUNT(*) FROM ad_spend ) AS strings_ad_spend
 FROM users """
pd.read_sql(query, conn)

,strings_users,strings_funnel_events,strings_test_results,strings_trial_lessons,strings_payments,strings_ad_spend
0,1500,5570,986,361,163,1620

## Уникальность user_id в таблице users

Вывод: Все пользователи уникальны(Дубликаты юзеров создают искажение относительно conversion rate )

In [10]:
query = """
SELECT DISTINCT COUNT(*) AS unique_users
,(SELECT COUNT(*)  FROM users) AS not_unique_users 
FROM users 

"""
pd.read_sql(query, conn)

   unique_users  not_unique_users
0          1500              1500

## Есть ли пользователи в событиях, которых нет в users

Вывод: Аномальных ID не обнаружено(Перед проблемных мест в пути пользователя по группам,нужно убедиться, что мы работаем с одинаковыми пользователями и данные собраны и интерпретированы правильно)

In [11]:
query = "SELECT DISTINCT user_id FROM  funnel_events WHERE user_id not in(SELECT DISTINCT user_id FROM users) "
pd.read_sql(query, conn)

Empty DataFrame
Columns: [user_id]
Index: []

## Пропуски в ключевых полях

Вывод:Аномальных пропусков не обнаружено,кроме случая если клиент не допроходил тест или не заканчивал пробный урок(Перед работой с данными нужно убедиться что данные полные,чтобы не было пустых значеный или непральных в выводах )

### Пропуски user_id

In [12]:
query = """SELECT COUNT(*) AS id_null_users
 ,(SELECT COUNT(*) FROM funnel_events WHERE user_id IS NULL ) AS id_null_funnel_events
 ,(SELECT COUNT(*) FROM payments WHERE user_id IS NULL) AS id_null_payments
 ,(SELECT COUNT(*) FROM trial_lessons WHERE user_id IS NULL) AS id_null_trial_lessons
 ,(SELECT COUNT(*) FROM test_results WHERE user_id IS NULL) AS id_null_test_results
 FROM users WHERE user_id IS NULL
 """
pd.read_sql(query, conn)

,id_null_users,id_null_funnel_events,id_null_payments,id_null_trial_lessons,id_null_test_results
0,0,0,0,0,0

### Пропуски event_name и event_time

In [13]:
query = "SELECT COUNT(*) FROM funnel_events WHERE event_name IS NULL"
pd.read_sql(query, conn)

   COUNT(*)
0         0

In [14]:
query = "SELECT COUNT(*) FROM funnel_events WHERE event_time IS NULL"
pd.read_sql(query, conn)

   COUNT(*)
0         0

### Пропуски acquisition_channel

In [15]:
query = """
SELECT COUNT(*) AS channel_null_funnel_events
,(SELECT COUNT(*) FROM payments WHERE acquisition_channel IS NULL) AS channel_null_payments
,(SELECT COUNT(*) FROM ad_spend WHERE acquisition_channel IS NULL) AS channel_null_ad_spend
,(SELECT COUNT(*) FROM users WHERE acquisition_channel IS NULL) AS channel_null_users
FROM funnel_events WHERE acquisition_channel IS NULL
"""
pd.read_sql(query, conn)

,channel_null_funnel_events,channel_null_payments,channel_null_ad_spend,channel_null_users
0,0,0,0,0

### Пропуски payment_status and amount_eur

In [16]:
query = "SELECT COUNT(*) FROM payments WHERE payment_status IS NULL"
pd.read_sql(query, conn)

   COUNT(*)
0         0

In [17]:
query = "SELECT COUNT(*) FROM payments WHERE amount_eur  IS NULL"
pd.read_sql(query, conn)

   COUNT(*)
0         0

### Провека всех строк

In [18]:
trial_lessons = pd.read_sql("SELECT * FROM trial_lessons", conn)
print(trial_lessons.isnull().sum())
print()
test_results = pd.read_sql("SELECT * FROM test_results", conn)
print(test_results.isnull().sum())
print()
users = pd.read_sql("SELECT * FROM users", conn)
print(users.isnull().sum())
print()
ad_spend = pd.read_sql("SELECT * FROM ad_spend", conn)
print(ad_spend.isnull().sum())
print()
funnel_events = pd.read_sql("SELECT * FROM funnel_events", conn)
print(funnel_events.isnull().sum())
print()
payments = pd.read_sql("SELECT * FROM payments", conn)
print(payments.isnull().sum())

user_id               0
trial_booked_at       0
trial_attended_at    79
trial_attended        0
teacher_rating       79
dtype: int64

user_id                0
test_started_at        0
test_completed_at    136
test_score           136
recommended_level    136
recommended_plan     136
dtype: int64

user_id                0
first_visit_at         0
acquisition_channel    0
campaign               0
device                 0
age_group              0
country                0
landing_page           0
user_goal              0
dtype: int64

date                   0
acquisition_channel    0
campaign               0
spend_eur              0
impressions            0
clicks                 0
dtype: int64

event_id               0
user_id                0
event_time             0
event_name             0
step_order             0
acquisition_channel    0
campaign               0
dtype: int64

payment_id             0
user_id                0
payment_date           0
plan_name              0
subscription_type      0
amount_eur             0
payment_status         0
refund_flag            0
acquisition_channel    0
campaign               0
dtype: int64

## Дубликаты событий

Вывод:Дубликатов не выяылено (Для работы с категориями событий нужно убедиться,что нет дубликатов).

In [19]:
query = """SELECT DISTINCT COUNT(*) AS unique_events
,(SELECT COUNT(*) FROM funnel_events ) AS not_unique_events
FROM funnel_events

 """
pd.read_sql(query, conn)

   unique_events  not_unique_events
0           5570               5570

## Корректность дат

Вывод: Аномалий с датами не обнаружено (Для коректного рассчёта по периодам)

In [20]:
query = """ 
WITH tb AS( SELECT user_id
,event_time AS t1
,LAG(event_time,1) OVER(PARTITION BY user_id ORDER BY event_time) AS t2
FROM funnel_events  )


SELECT user_id, t1 AS event_time FROM tb
 WHERE
        t1 < t2         

"""

pd.read_sql(query, conn)

Empty DataFrame
Columns: [user_id, event_time]
Index: []

## Корректность Платежей

ВЫВОДЫ: 

1.Аномальных айди платежей не выявлено, система платежей не плодит дубликаты платежей

2.Пользователи у которых платёж не прошёл - не возвращались к оплате снова

3.Нет ни одного возврата

4.22.7% ошибок платежа

ГИПОТЕЗЫ:

1.Не работают возвраты

2.Для повторной оплаты система создаёт новый айди пользователя и клиент вводит некоректные данные

3.Недостаточное количество вариантов платежей для клиента, вследствии чего нет попыток повторной оплаты

4.Процент неудачных платежей весомый,соотвественно ошибки в платежах вызваны не только пользователями,но и некоректной работы терминала оплаты

РЕКОМЕНДАЦИИ:

1.Проверить коректность работы возвратов

2.Проверить коректность работы терминала оплаты или сбора данных с него

3.В случае коректной работы всех систем, Для пользователей которые ушли с ошибкой, провести ретаргетинг с предложением о скидке + Email-рассылку

In [21]:
query = """
SELECT payment_id AS sc_fl
,(SELECT payment_id FROM payments WHERE payment_status = 'refunded' and payment_status = 'failed') AS rf_fl 
 FROM payments WHERE payment_status = 'success' and payment_status = 'failed' 

"""
pd.read_sql(query, conn)

Empty DataFrame
Columns: [sc_fl, rf_fl]
Index: []

In [22]:
query = """
SELECT user_id 
,COUNT(payment_id) AS cnt_status
 FROM payments GROUP BY user_id   HAVING COUNT(payment_id) > 1

"""
pd.read_sql(query, conn)

Empty DataFrame
Columns: [user_id, cnt_status]
Index: []

In [23]:
query = """
SELECT COUNT(*)

 FROM payments WHERE payment_status = 'refunded'

"""
pd.read_sql(query, conn)

   COUNT(*)
0         0

In [24]:
query = """
SELECT Round((1.0 *COUNT(*) / (SELECT COUNT(*) FROM payments) ) * 100 ,1) AS failed_percent
 FROM payments WHERE payment_status = 'failed'

"""
pd.read_sql(query, conn)

   failed_percent
0            22.7